Imports System
Imports System.Windows.Forms
Imports DevExpress.XtraCharts
Imports DevExpress.XtraCharts.Designer
Imports System.Linq

Namespace ConditionallyHideSeriesLabels
    Partial Public Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Create a new DataSet
            Dim xmlDataSet As New System.Data.DataSet("XML DataSet")
            ' Load the XML document to the DataSet
            xmlDataSet.ReadXml("Data\GDPofG7.xml")
            ' This line of code is generated by Data Source Configuration Wizard
            chartControl1.DataSource = xmlDataSet.Tables("GDP")

            chartControl1.SeriesTemplate.ArgumentDataMember = "Year"
            chartControl1.SeriesTemplate.ValueDataMembers.AddRange("Product")
        End Sub

        Private Sub chartControl1_CustomDrawSeriesPoint(ByVal sender As Object, ByVal e As CustomDrawSeriesPointEventArgs) Handles chartControl1.CustomDrawSeriesPoint
            ' If the value is less than 1, hide the point's label.

            Dim test = e.Series.Points.Max(Function(p) p.ArgumentX.NumericalArgument)

            If Not e.Series.Points.Max(Function(p) p.ArgumentX.NumericalArgument).Equals(e.SeriesPoint.NumericalArgument) Then
                e.LabelText = ""
            End If
        End Sub
    End Class
End Namespace